name: PullRequest Validation

on:
  pull_request:
    types: [opened, synchronize]

env:
  ResourceGroupName: "anmgh-rg"
  ResourceGroupLocation: "westeurope"

jobs:
  deploy-from--main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: "main"
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Login with Azure CLI
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            if $(az group exists --name ${{ env.ResourceGroupName }}) ; then
              echo "Azure resource group already exists, skipping creation..."
            else
              az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
              echo "Azure resource group created"
            fi
      - name: Check file existence
        id: check_file
        uses: andstor/file-existence-action@v1
        with:
          files: "./challenges/templates/challenge_05/hubspoke.json"
      - name: Deploy from main branch
        uses: azure/arm-deploy@v1
        if: steps.check_file.outputs.files_exists == 'true'
        with:
          resourceGroupName: ${{ env.ResourceGroupName }}
          template: "./challenges/templates/challenge_05/hubspoke.json"
          parameters: winVmUser='moog' winVmPassword='change@me1234?' winVmDnsPrefix='hspnm'

  what-if-deployment:
    runs-on: ubuntu-latest
    needs: deploy-from--main

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: What-if deployment
        shell: bash
        run: |
          CHANGES="$(az deployment group what-if -n demo01 -g ${{ env.ResourceGroupName }}  --template-file ./challenges/templates/challenge_05/hubspoke.json  --parameters winVmUser=moog winVmPassword=change@me1234? winVmDnsPrefix=hspnm)"
          TEXT="$(printf "\`\`\`Text\n%s\n\`\`\`" "$(echo "$CHANGES")")"
          RESULT="$(echo "$TEXT" | sed s/\"/'\\\"'/g | sed s/\`/'\\\`'/g)"
          RESULT="${RESULT//'%'/'%25'}"
          RESULT="${RESULT//$'\n'/'%0A'}"
          RESULT="${RESULT//$'\r'/'%0D'}"
          echo "::set-output name=changes::$RESULT"
        id: what-if-deployment
      - uses: actions/github-script@v3
        with: 
          github-token: ${{ github.token }}
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{ steps.what-if-deployment.outputs.changes }}`
            })
