name: Variable test

on:
  workflow_dispatch:

jobs:
  variable-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Show Azure Account
        run: az account show
      - name: Set Variable
        run: echo ::set-output name=myvariable::myvalue
        id: set-variable
      - name: Display Variable
        run: echo '${{ steps.set-variable.outputs.myvariable }}'  
      - name: What-If deployment
        run: echo ::set-output name=chnages::$(az deployment group what-if -n demo01 -g hsp-rg  --template-file ./challenges/templates/challenge_05/hubspoke.json  --parameters winVmUser='moog' winVmPassword='change@me1234?' winVmDnsPrefix='hspnm')
        id: what-if-deployment
      - name: what-if-output
        run: echo '${{ steps.what-if-deployment.changes }}'