name: Variable test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate-what-if:
    runs-on: ubuntu-latest

    steps:
      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - name: What-If deployment
      #   run: echo ::set-output name=changes::$(az deployment group what-if -n demo01 -g hsp-rg  --template-file ./challenges/templates/challenge_05/hubspoke.json  --parameters winVmUser='moog' winVmPassword='change@me1234?' winVmDnsPrefix='hspnm')
      #   id: what-if-deployment
      - name: What-if deployment
        shell: bash
        run: |
          CHANGES="$(az deployment group what-if -n demo01 -g hsp-rg  --template-file ./challenges/templates/challenge_05/hubspoke.json  --parameters winVmUser='moog' winVmPassword='change@me1234?' winVmDnsPrefix='hspnm' --no-pretty-print)"
          echo "$CHANGES"
          JSON="$(printf "\`\`\`JSON\n%s\n\`\`\`" "$(echo "$CHANGES")")"
          echo "$JSON"
          RESULT="$(echo "$JSON" | sed s/\"/'\\\"'/g | sed s/\`/'\\\`'/g)"
          echo "----------------------------------------------------------------------"
          echo "$RESULT"
          echo "----------------------------------------------------------------------"
          RESULT="${RESULT//'%'/'%25'}"
          RESULT="${RESULT//$'\n'/'%0A'}"
          RESULT="${RESULT//$'\r'/'%0D'}"
          echo "$RESULT"
          echo "::set-output name=changes::$RESULT"
        id: what-if-deployment
      - name: What-if-output
        run: echo "${{ steps.what-if-deployment.outputs.changes }}"
      - uses: actions/github-script@v3
        with: 
          github-token: ${{ github.token }}
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `"${{ steps.what-if-deployment.outputs.changes }}"`
            })